name: CI

on:
  pull_request:
    branches: [ "develop", "master" ]
  push:
    branches: [ "develop", "master" ]

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install NPM dependencies
        run: npm ci
      - name: Jest testing
        run: npm test
      - name: Test Report
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: JEST Tests
          path: reports/jest-*.xml
          reporter: jest-junit
